name: Coveralls

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coveralls:
    runs-on: ubuntu-latest

    steps:
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
